
services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "9876:9876"
    volumes:
      - ./app:/app
    command: >
      /bin/sh -c "python manage.py makemigrations &&
                  python manage.py migrate &&
                  python manage.py wait_for_db &&
                  python manage.py runserver 0.0.0.0:9876"
    environment:
      # Adding database service environment variables to connect from the app service
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=changeme
    depends_on:
      - db

  # Adding the database service
  db:
    image: postgres:13-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme

# Volume service stores db data in container
volumes:
  dev-db-data: